Fix Code Examples for Bubble Sort
acm-ucr/r-tools pull request #163
Opened 2024-01-14 21:49 UTC by aorde0012

![bubbleSortPython](https://github.com/acm-ucr/r-tools/assets/134166874/0ed3bd39-3743-4615-bca1-ac81acb73764)
![bubbleSorthJS](https://github.com/acm-ucr/r-tools/assets/134166874/01619bce-7685-4f9e-81ba-4e9cf948011c)
![bubbleSortC++](https://github.com/acm-ucr/r-tools/assets/134166874/fe609d20-ec58-49af-9fb6-9d68470d8427)

- Updated examples for bubbleSort to include arrow functions.
- Made comment spacing consistent
- Transitioned to template literals

2024-01-14 22:40 UTC, menthy-wu requested changes

2024-01-14 22:40 UTC, menthy-wu commented on src/util/sort/bubbleSort.js
> +  "C++": `#include <iostream>
can you change the array to vector.

2024-01-16 21:08 UTC, aorde0012 commented on src/util/sort/bubbleSort.js
> +  "C++": `#include <iostream>
changed array to vector for C++ example, are there additional changes needed?

2024-01-18 18:44 UTC, menthy-wu approved these changes

2024-01-18 18:44 UTC, merged